
TARGET = csg
TEMPLATE = lib
CONFIG += staticlib debug

QMAKE_CXXFLAGS += -Wall
QMAKE_CXXFLAGS += -DNO_TEMPLATE_IMPLEMENTATION
QMAKE_CXXFLAGS_DEBUG -= -g
QMAKE_CXXFLAGS_DEBUG += -ggdb

INCLUDEPATH += ../vectorMatrix ../image

SOURCES += *.cpp

HEADERS += *.h

DESTDIR = ../lib
